services:
  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./Server:/app
      - /app/node_modules